<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE document [
        <!ELEMENT document (employee)*>
        <!ELEMENT employee (name+, hiredate?, projects*)>
        <!ELEMENT name (lastName, fistName)>
        <!ELEMENT lastName (#PCDATA)>
        <!ELEMENT fistName (#PCDATA)>
        <!ELEMENT hiredate (#PCDATA)>
        <!ELEMENT projects (project)*>
        <!ELEMENT project (product,id,price)>
        <!ELEMENT product (#PCDATA)>
        <!ELEMENT id (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
]>
<document>
    <employee>
        <name>
            <lastName>Kelly</lastName>
            <fistName>Grace</fistName>
        </name>
        <hiredate>October 15,2005</hiredate>
        <projects>
            <project>
                <product>Printer</product>
                <id>111</id>
                <price>$110.0</price>
            </project>
        </projects>
    </employee>
</document>