=== Khanhvnth1908/HomeWorkOnline/Student.dtd
<!ELEMENT FPTAPTECH (STUDENTS)*>
<!ELEMENT STUDENTS (NAME+,AGE+))>
<!ELEMENT NAME (FISTNAME,LASTNAME)>
<!ELEMENT FISTNAME (#PCDATA)>
<!ELEMENT LASTNAME (#PCDATA)>
<!ELEMENT AGE (#PCDATA)>

<!ATTLIST STUDENTS SEX (Female|Male) "Female">
<!ATTLIST AGE>

=== Khanhvnth1908/HomeWorkOnline/Student.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE FPTAPTECH SYSTEM "Student.dtd">
<FPTAPTECH>
    <STUDENTS SEX="Female">
        <NAME>
            <FISTNAME>Chi</FISTNAME>
            <LASTNAME>Pham</LASTNAME>
        </NAME>
        <AGE>17</AGE>
    </STUDENTS>
    <STUDENTS SEX="Female">
        <NAME>
            <FISTNAME>Quan</FISTNAME>
            <LASTNAME>Vuong</LASTNAME>
        </NAME>
        <AGE>22</AGE>
    </STUDENTS>
    <STUDENTS SEX="Male">
        <NAME>
            <FISTNAME>Khanh</FISTNAME>
            <LASTNAME>Vuong</LASTNAME>
        </NAME>
        <AGE>18</AGE>
    </STUDENTS>
</FPTAPTECH>
